[package]
name = "forge_ecs"
version = "0.1.0"
edition = "2021"

[lib]
name = "forge_ecs"
path = "src/lib.rs"

[features]
default = ["file-dialog"]
file-dialog = ["dep:rfd"]

[[bin]]
name = "demo"
path = "demo/main.rs"

[[bin]]
name = "game"
path = "demo/game.rs"

[[bin]]
name = "editor"
path = "demo/editor.rs"

[[bin]]
name = "ctf"
path = "demo/ctf.rs"

[dependencies]
arboard = { version = "3.6.1", default-features = false, features = [
    "wayland-data-control",
] }
clap = { version = "4.5", features = ["derive", "env"] }
bincode = "1.3"
rand = "0.8"
renet = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
winit = "0.30"
wgpu = "25"
imgui = { version = "0.12", features = ["docking"] }
imgui-wgpu = "0.25"
imgui-winit-support = "0.13"
bytemuck = { version = "1.14", features = ["derive"] }
pollster = "0.3"
rfd = { version = "0.15", default-features = false, features = ["gtk3"], optional = true }

[[bin]]
name = "gen_ctf_arenas"
path = "src/bin/gen_ctf_arenas.rs"

[[bin]]
name = "matchmaker"
path = "src/bin/matchmaker.rs"

[[bin]]
name = "matchmaker_client"
path = "src/bin/matchmaker_client.rs"
